### PR TITLE
Fix some typos in README.md

### PR DESCRIPTION
**Pull request by nitkon**
Fix a couple of typos.

### CODE REVIEW

**Comment by jodh-intel** [comment]
Thanks for raising @nitkon!

However, please could you update the commit to include an issue number and "subsystem" as explained here:

- https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format

**Review by egernst — APPROVED** [review]

**Comment by jodh-intel** [comment]
lgtm

**Comment by jodh-intel** [comment]
CI is failing due to #54 but this PR is clearly doc only, so merging...

**Pull request merged**
