### PR TITLE
Typo fix: add missing `make` command

### PR DESCRIPTION
**Pull request by t3hmrman**

### CODE REVIEW

**Review by grahamwhaley — APPROVED** [review]
lgtm
The CI failed - I suspect for two reaons:
1) I think the commit needs to conform to the patch format as detailed in: https://github.com/clearcontainers/runtime/blob/master/CONTRIBUTING.md#patch-format - that is, you'll need to add an Issue and reference it in a `Fixes` line, and sign off your commit.

Also, the CI seems to have gotten some odd build error:
```
15:02:11 /workdir/linux /workdir
15:02:12 scripts/kconfig/conf  --silentoldconfig Kconfig
15:02:13 Makefile:943: *** "Cannot generate ORC metadata for CONFIG_UNWINDER_ORC=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel".  Stop.
```
/cc @jcvenegas @chavafg for thoughts on that.

btw @t3hmrman , have you considered https://github.com/kata-containers/, which is where the primary and leading edge development has shifted to (and with the 1.0 release last week, it is probably the best place to head...)

**Comment by t3hmrman** [comment]
About the two things:

1. Ahhh OK, I will go ahead and make an issue and fix up the patch format!

2. That actually has to do with [newer kernels requiring the libelf dev](https://github.com/ivandavidov/minimal/issues/141) (?) -- I've been running into this a lot, it turns out for newer versions you need to `dnf install elfutils-libelf-devel`, I made the change locally in the `Dockerfile` but forgot about it.

Also @grahamwhaley , yeah, I'm actually trying to get kata-containers running on Container Linux (CoreOS) -- it's been an long ride but basically I've statically compiled `kata-runtime`, `kata-proxy`, `kata-shim`, and a minimal build of `qemu-system-x86_64` since it doesn't come with Container Linux releases currently.

After the static building I was trying to get it running under [`containerd`'s untrusted workloads (new in `v1.1.0`)](https://github.com/containerd/containerd/releases/tag/v1.1.0), then I realized I didn't have an image to feed to `kata` just sitting around and couldn't find one... so I found this project.

**Comment by t3hmrman** [comment]
I've added the `Dockerfile` change  I was making locally so maybe the Jenkins build will pass now, while I look at the patch format

[EDIT] - Looking at [the patch format docs](https://github.com/clearcontainers/runtime/blob/master/CONTRIBUTING.md#patch-format) does it actually apply to Github PRs? I assume the sign off footer should go into the squashed commit?

**Comment by grahamwhaley** [comment]
Yeah, the sign off needs to be in the commits (each commit).
You only need one Fixes in a commit message per PR
Oh, btw, kata has its own osbuilder as well, that also does initrd images:
https://github.com/kata-containers/osbuilder

**Comment by t3hmrman** [comment]
Thanks for clarifying -- if the build passes I'll go ahead and squash the commits and fix the commit message.

Thanks for the link to the other osbuilder, I'll make sure to use that in the future!

**Comment by t3hmrman** [comment]
Hey @grahamwhaley I've fixed up the commit mesage, please let me know if anything else needs to be changed.

**Comment by t3hmrman** [comment]
Just realized I filed the ticket in the wrong place (`clearcontainers/runtime`), #54 is the right one, so I updated the commit message to reflect it

**Comment by grahamwhaley** [comment]
Sorry for the delay there @t3hmrman  - my email system started to 'eat' emails for some reason, and I didn't see this. All green ... merging!

**Comment by t3hmrman** [comment]
No problem @grahamwhaley , glad I contribute a tiny bit to help -- thanks for all the work on the project!

**Pull request merged**
